/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compress(data: Buffer, level?: number | undefined | null): Promise<Buffer>
export function decompress(data: Buffer): Promise<Buffer>
