/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function compress(data: Buffer, level?: number | undefined | null): Promise<Buffer>
export declare function decompress(data: Buffer): Promise<Buffer>
